import { AfterViewInit, ElementRef, Injector, OnInit, QueryList } from '@angular/core';
import { TypeaheadContainerComponent, TypeaheadDirective, TypeaheadMatch } from 'ngx-bootstrap';
import { DataSetItem } from '../../../utils/form-utils';
import { DatasetAwareFormComponent } from '../base/dataset-aware-form.component';
export declare class SearchComponent extends DatasetAwareFormComponent implements OnInit, AfterViewInit {
    binddatavalue: any;
    binddataset: any;
    static initializeProps: void;
    casesensitive: boolean;
    searchkey: string;
    queryModel: Array<DataSetItem> | string;
    query: string;
    limit: any;
    showsearchicon: boolean;
    minchars: number;
    type: string;
    navsearchbar: any;
    debouncetime: number;
    private typeaheadDataSource;
    private pagesize;
    private page;
    _loadingItems: boolean;
    private dataProvider;
    private result;
    private formattedDataset;
    private isformfield;
    private $typeaheadEvent;
    tabindex: number;
    startIndex: number;
    binddisplaylabel: string;
    typeaheadContainer: TypeaheadContainerComponent;
    typeahead: TypeaheadDirective;
    ulElement: ElementRef;
    liElements: QueryList<ElementRef>;
    private allowonlyselect;
    private class;
    private lastSelectedIndex;
    private dataoptions;
    dropdownEl: any;
    private _lastQuery;
    private _lastResult;
    private _isOpen;
    private showClosebtn;
    private _unsubscribeDv;
    private _datasource;
    private isScrolled;
    private parentEl;
    private position;
    private elIndex;
    private listenQuery;
    private _domUpdated;
    private searchon;
    matchmode: string;
    datasource: any;
    constructor(inj: Injector, binddatavalue: any, binddataset: any);
    private clearSearch;
    private closeSearch;
    private renderMobileAutoComplete;
    private getDataSourceAsObservable;
    protected handleEvent(node: HTMLElement, eventName: string, eventCallback: Function, locals: any): void;
    private highlight;
    private insertAtIndex;
    private isMobileAutoComplete;
    private loadMoreData;
    private onFocusOut;
    private onInputChange;
    private handleEnterEvent;
    private onSelect;
    private onBeforeservicecall;
    private onDropdownOpen;
    private selectNext;
    private setLastActiveMatchAsSelected;
    private triggerSearch;
    private isUpdateOnKeyPress;
    private debounceDefaultQuery;
    private updateByDatavalue;
    private updateByDataSource;
    private updateDatavalueFromQueryModel;
    private updateByDataset;
    getDataSource(query: Array<string> | string, searchOnDataField?: boolean, nextItemIndex?: number): Promise<DataSetItem[]>;
    getTransformedData(data: any, itemIndex?: number, iscustom?: boolean): DataSetItem[];
    onScroll($scrollEl: Element, evt: Event): void;
    ngOnInit(): void;
    ngAfterViewInit(): void;
    typeaheadOnSelect(match: TypeaheadMatch, $event: Event): void;
    onPropertyChange(key: string, nv: any, ov: any): void;
}
