import { AfterViewInit, Injector, OnDestroy } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Subject } from 'rxjs';
import { AbstractI18nService, AbstractNavigationService, App } from '@wm/core';
import { AppManagerService } from '../services/app.manager.service';
import { FragmentMonitor } from '../util/fragment-monitor';
export declare abstract class BasePageComponent extends FragmentMonitor implements AfterViewInit, OnDestroy {
    Widgets: any;
    Variables: any;
    Actions: any;
    App: App;
    injector: Injector;
    pageName: string;
    activePageName: string;
    route: ActivatedRoute;
    appManager: AppManagerService;
    navigationService: AbstractNavigationService;
    router: Router;
    pageParams: any;
    showPageContent: boolean;
    i18nService: AbstractI18nService;
    appLocale: any;
    startupVariablesLoaded: boolean;
    pageTransitionCompleted: boolean;
    destroy$: Subject<{}>;
    viewInit$: Subject<{}>;
    abstract evalUserScript(prefabContext: any, appContext: any, utils: any): any;
    abstract getVariables(): any;
    init(): void;
    registerWidgets(): void;
    initUserScript(): void;
    registerPageParams(): void;
    registerDestroyListener(fn: Function): void;
    defineI18nProps(): void;
    initVariables(): void;
    runPageTransition(transition: string): Promise<void>;
    invokeOnReady(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    onReady(): void;
    onBeforePageLeave(): void;
    onPageContentReady(): void;
}
